# Generated by Django 5.2.11 on 2026-04-09 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('ONE SIZE', 'One Size'), ('28', '28'), ('30', '30'), ('32', '32'), ('34', '34'), ('36', '36'), ('38', '38'), ('3-4Y', '3-4Y'), ('5-6Y', '5-6Y'), ('7-8Y', '7-8Y'), ('9-10Y', '9-10Y'), ('11-12Y', '11-12Y')], max_length=20)),
                ('color', models.CharField(blank=True, choices=[('black', 'Black'), ('white', 'White'), ('grey', 'Grey'), ('navy', 'Navy'), ('blue', 'Blue'), ('red', 'Red'), ('green', 'Green'), ('beige', 'Beige'), ('brown', 'Brown'), ('pink', 'Pink'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('purple', 'Purple'), ('multicolor', 'Multicolor')], max_length=20)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.product')),
            ],
            options={
                'ordering': ['size'],
                'unique_together': {('product', 'size', 'color')},
            },
        ),
    ]
