# Generated by Django 5.2.11 on 2026-04-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(blank=True, choices=[('', 'None'), ('new', 'New Arrival'), ('sale', 'Sale'), ('best_seller', 'Best Seller'), ('featured', 'Featured')], default='', max_length=20),
        ),
    ]
