# Generated by Django 5.2.12 on 2026-05-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='gender',
        ),
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('face', 'Face Care'), ('body', 'Body Care'), ('hair', 'Hair Care'), ('makeup', 'Makeup'), ('wellness', 'Wellness')], default='face', max_length=20),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.CharField(blank=True, choices=[('unscented', 'Unscented'), ('citrus', 'Citrus'), ('floral', 'Floral'), ('mint', 'Mint'), ('rose', 'Rose'), ('vanilla', 'Vanilla'), ('herbal', 'Herbal'), ('fruity', 'Fruity')], max_length=20),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(choices=[('30ml', '30 ml'), ('50ml', '50 ml'), ('100ml', '100 ml'), ('150ml', '150 ml'), ('200ml', '200 ml'), ('250ml', '250 ml'), ('500ml', '500 ml'), ('1L', '1 L')], max_length=20),
        ),
    ]
